try updating taler-exchange to 0.9.3a
Seems like gnunet crypto library is missing:

taler-exchange> ../../src/include/taler_crypto_lib.h:3621:15: warning: 'union GNUNET_CRYPTO_BlindingSecretP' declared inside parameter list will not be visible outside of this definition or declaration
taler-exchange>  3621 |   const union GNUNET_CRYPTO_BlindingSecretP *coin_bks,
taler-exchange>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taler-exchange> ../../src/include/taler_crypto_lib.h:5867:46: error: field 'cipher' has incomplete type
taler-exchange>  5867 |   enum GNUNET_CRYPTO_BlindSignatureAlgorithm cipher;
taler-exchange>       |                                              ^~~~~~
taler-exchange> ../../src/include/taler_crypto_lib.h:3638:15: warning: 'union GNUNET_CRYPTO_BlindingSecretP' declared inside parameter list will not be visible outside of this definition or declaration
taler-exchange>  3638 |   const union GNUNET_CRYPTO_BlindingSecretP *coin_bks,
taler-exchange>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taler-exchange> ../../src/include/taler_crypto_lib.h:3654:15: warning: 'union GNUNET_CRYPTO_BlindingSecretP' declared inside parameter list will not be visible outside of this definition or declaration
taler-exchange>  3654 |   const union GNUNET_CRYPTO_BlindingSecretP *coin_bks,
taler-exchange>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taler-exchange> ../../src/include/taler_crypto_lib.h:5867:46: error: field 'cipher' has incomplete type
taler-exchange>  5867 |   enum GNUNET_CRYPTO_BlindSignatureAlgorithm cipher;
taler-exchange>       |